name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        # v.0.3.6 - This is the version where packaging format changed from zip to tar
        tf-summarize-versions: [ v0.3.1, v0.3.6, latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup tf-summarize - ${{ matrix['tf-summarize-versions'] }}
        uses: ./
        with:
          tf-summarize-version: ${{ matrix['tf-summarize-versions'] }}

      - name: Validate tf-summarize version - When exact version is specified
        if: ${{ matrix['tf-summarize-versions'] != 'latest' }}
        shell: bash
        run: |
          actual_version=v$(tf-summarize -v | awk -F ': ' '{ print $2 }')
          expected_version=${{ matrix['tf-summarize-versions'] }}
          
          if [ "$actual_version" == "$expected_version" ]; then
            echo "Test succeeded"
          else
            echo "Versions are different"
            echo "Actual: ${actual_version}"
            echo "Expected: ${expected_version}"
            exit 1
          fi

      - name: Validate tf-summarize Version - When exact version is not specified
        if: ${{ matrix['tf-summarize-versions'] == 'latest' }}
        run: tf-summarize -v

