name: 'build-test'

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          npm install
      - run: |
          npm run all

  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        # v.0.3.6 - This is the version where packaging format changed from zip to tar
        tf-summarize-versions: [ v0.3.1, v0.3.6, latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup tf-summarize - ${{ matrix['tf-summarize-versions'] }}
        uses: ./
        with:
          tf-summarize-version: ${{ matrix['tf-summarize-versions'] }}

      - name: Validate tf-summarize version - When exact version is specified
        if: ${{ matrix['tf-summarize-versions'] != 'latest' }}
        shell: bash
        run: |
          actual_version=v$(tf-summarize -v | awk -F ': ' '{ print $2 }')
          expected_version=${{ matrix['tf-summarize-versions'] }}
     
          if [ "$actual_version" == "$expected_version" ]; then
            echo "Test succeeded"
          else
            echo "Versions are different"
            echo "Actual: ${actual_version}"
            echo "Expected: ${expected_version}"
            exit 1
          fi

      - name: Validate tf-summarize Version - When exact version is not specified
        if: ${{ matrix['tf-summarize-versions'] == 'latest' }}
        run: tf-summarize -v
